version: '3.9'

services:
    frontend:
        build: .
        container_name: movie-ticket-frontend
        ports:
            - '3001:80'
        restart: always
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost/health']
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
